### Create a new flowchart
POST http://localhost:3002/flowchart
Content-Type: application/json

{
  "name": "New Flowchart",
  "description": "This is a new flowchart",
  "projectId": "1",
  "definitionASL": {
    "StartAt": "InitialState",
    "States": {
      "InitialState": {
        "Type": "Pass",
        "End": true
      }
    }
  }
}

### Deploy a flowchart
POST http://localhost:3002/flowchart/1/deploy

### Execute a flowchart
POST http://localhost:3002/flowchart/1/execute



### Get all flowchart
GET http://localhost:3002/flowchart?projectId=1

### Get a flowchart by ID
GET http://localhost:3002/flowchart/1

### Update a flowchart
PATCH http://localhost:3002/flowchart/1
Content-Type: application/json

{
  "name": "Updated Flowchart Name",
  "description": "Updated description of the flowchart"
}

### Delete a flowchart
DELETE http://localhost:3002/flowchart/1

