### Create a new project
POST http://localhost:3002/project
Content-Type: application/json

{
  "name": "New Project",
  "description": "This is a new project"
}

### Get all project
GET http://localhost:3002/project?page=1

### Get a project by ID
GET http://localhost:3002/project/1

### Update a project
PATCH http://localhost:3002/project/1
Content-Type: application/json

{
  "name": "Updated Project Name",
  "description": "Updated description of the project"
}

### Delete a project
DELETE http://localhost:3002/project/1
